# Generated by Django 4.2.7 on 2025-09-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_timebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltimeboxsession',
            name='outcome',
            field=models.CharField(blank=True, choices=[('completed', 'Completed Successfully'), ('partial', 'Partially Completed'), ('interrupted', 'Interrupted'), ('abandoned', 'Abandoned')], max_length=20, null=True),
        ),
    ]
